SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `tc_almanac` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `solar_date` DATE NOT NULL COMMENT '公历日期',
    `lunar_date` VARCHAR(50) DEFAULT '' COMMENT '农历日期',
    `lunar_year` VARCHAR(20) DEFAULT '' COMMENT '农历年',
    `lunar_month` TINYINT DEFAULT NULL COMMENT '农历月',
    `lunar_day` TINYINT DEFAULT NULL COMMENT '农历日',
    `ganzhi_year` VARCHAR(10) DEFAULT '' COMMENT '年柱干支',
    `ganzhi_month` VARCHAR(10) DEFAULT '' COMMENT '月柱干支',
    `ganzhi_day` VARCHAR(10) DEFAULT '' COMMENT '日柱干支',
    `ganzhi` VARCHAR(10) DEFAULT '' COMMENT '兼容后台展示的干支字段',
    `nayin` VARCHAR(50) DEFAULT '' COMMENT '纳音',
    `wuxing` VARCHAR(50) DEFAULT '' COMMENT '五行',
    `constellation` VARCHAR(20) DEFAULT '' COMMENT '星座',
    `xingsu` VARCHAR(20) DEFAULT '' COMMENT '星宿',
    `pengzu` VARCHAR(100) DEFAULT '' COMMENT '彭祖百忌',
    `yi` JSON NULL COMMENT '宜事项',
    `ji` JSON NULL COMMENT '忌事项',
    `chong` VARCHAR(10) DEFAULT '' COMMENT '冲',
    `sha` VARCHAR(10) DEFAULT '' COMMENT '煞方',
    `chong_desc` VARCHAR(200) DEFAULT '' COMMENT '冲煞说明',
    `zhiri` VARCHAR(10) DEFAULT '' COMMENT '十二值日',
    `xiu` VARCHAR(20) DEFAULT '' COMMENT '二十八宿',
    `taishen` VARCHAR(100) DEFAULT '' COMMENT '胎神占方',
    `jishen` JSON NULL COMMENT '吉神',
    `xiongsha` JSON NULL COMMENT '凶煞',
    `shichen` JSON NULL COMMENT '时辰吉凶',
    `shengxiao_teji` VARCHAR(50) DEFAULT '' COMMENT '特吉生肖',
    `shengxiao_ciji` VARCHAR(50) DEFAULT '' COMMENT '次吉生肖',
    `shengxiao_daidai` VARCHAR(50) DEFAULT '' COMMENT '带衰生肖',
    `fangwei_xishen` VARCHAR(20) DEFAULT '' COMMENT '喜神方位',
    `fangwei_caishen` VARCHAR(20) DEFAULT '' COMMENT '财神方位',
    `fangwei_fushen` VARCHAR(20) DEFAULT '' COMMENT '福神方位',
    `fangwei_yanggui` VARCHAR(20) DEFAULT '' COMMENT '阳贵神方位',
    `fangwei_yingui` VARCHAR(20) DEFAULT '' COMMENT '阴贵神方位',
    `is_jieqi` TINYINT DEFAULT 0 COMMENT '是否节气日',
    `jieqi_name` VARCHAR(20) DEFAULT '' COMMENT '节气名称',
    `status` TINYINT DEFAULT 1 COMMENT '状态',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_solar_date` (`solar_date`),
    KEY `idx_status` (`status`),
    KEY `idx_jieqi` (`is_jieqi`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='黄历数据表';
