/**
 * 中国主要城市数据
 */
export const cityData = [
  { name: '北京市', province: '直辖市' },
  { name: '上海市', province: '直辖市' },
  { name: '天津市', province: '直辖市' },
  { name: '重庆市', province: '直辖市' },
  { name: '广州市', province: '广东省' },
  { name: '深圳市', province: '广东省' },
  { name: '杭州市', province: '浙江省' },
  { name: '南京市', province: '江苏省' },
  { name: '武汉市', province: '湖北省' },
  { name: '成都市', province: '四川省' },
  { name: '西安市', province: '陕西省' },
  { name: '郑州市', province: '河南省' },
  { name: '长沙市', province: '湖南省' },
  { name: '沈阳市', province: '辽宁省' },
  { name: '哈尔滨市', province: '黑龙江省' },
  { name: '济南市', province: '山东省' },
  { name: '青岛市', province: '山东省' },
  { name: '大连市', province: '辽宁省' },
  { name: '苏州市', province: '江苏省' },
  { name: '厦门市', province: '福建省' },
  { name: '福州市', province: '福建省' },
  { name: '合肥市', province: '安徽省' },
  { name: '昆明市', province: '云南省' },
  { name: '南昌市', province: '江西省' },
  { name: '贵阳市', province: '贵州省' },
  { name: '南宁市', province: '广西壮族自治区' },
  { name: '海口市', province: '海南省' },
  { name: '兰州市', province: '甘肃省' },
  { name: '银川市', province: '宁夏回族自治区' },
  { name: '西宁市', province: '青海省' },
  { name: '乌鲁木齐市', province: '新疆维吾尔自治区' },
  { name: '拉萨市', province: '西藏自治区' },
  { name: '呼和浩特市', province: '内蒙古自治区' },
  { name: '石家庄市', province: '河北省' },
  { name: '太原市', province: '山西省' },
  { name: '长春市', province: '吉林省' }
]
